org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.20.1
forge_version=47.2.0
mappings_channel=official

minecraft_version_range=[1.20.1,1.21)
forge_version_range=[47,)

mod_id=chathub
mod_name=ChatHub 2.0
mod_license=MIT
mod_version=2.0.0
mod_group_id=com.zhanganzhi.chathub
mod_authors=Andy Zhang, ZhuRuoLing, 401U, maoyihao